### ISSUE TITLE
GetBoard command

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Hanze-TwoPlayerGameServer#10]
Implement a protocol addition so you can receive the whole board, in case of desyncs or general errors

**Comment by johankladder** [comment]
Wouldn't this be game specific? As not every game on the server needs to have a board. Don't get me wrong, in this situation there is a board for every game. But for example when playing the GuessGame, there is no board to gather.

**Comment by IcyPalm** [comment]
Fair point, still, in case of boardgames not a bad idea in my opinion

**Comment by goto-bus-stop** [comment]
`get game state` 💪

**Comment by johankladder** [comment]
The server doesn't even know if there is a board or something more abstract. How would you implement that. I don't think this is necessary.

**Comment by goto-bus-stop** [comment]
I'm not sure that it's necessary, but game modules could provide a method:

```java
abstract public String getSerializedGameState();
```

**Comment by johankladder** [comment]
They could, you could also save all the String objects that have been send per challenge on the server. Only this gamestate will differ from all different kind of games.

**Comment by goto-bus-stop** [comment]
@IcyPalm wontfix? :package:

**Comment by IcyPalm** [comment]
Yeah....
