### ISSUE TITLE
Protocol Document

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Hanze-TwoPlayerGameServer#11]
We need a more elaborate document for the protocol

**Comment by knarfi** [comment]
I converted the protocol to english and put it in a markdown layout. Only the unsubscribe command is added. All the other desired changes should be discussed on Github with new issues. Besides, the changes should first be implemented before they are added to the protocol. If the pull request is accepted this issue can be closed.

**Comment by knarfi** [comment]
This issue can be closed :)
