### ISSUE TITLE
Deciding on how we format moves. 

### ISSUE THREAD

**Issue by OptOutOfSociety** [IcyPalm/Hanze-TwoPlayerGameServer#12]
The current server implementation uses strings as move to send to the clients.
We need to decide wether we format this string as [X,Y] or as row*max_rows+col.

**Comment by Bennyn92** [comment]
Preference of group 6: [X, Y]. 
(Isn't there a poll option here on Git?)

**Comment by Bennyn92** [comment]
Is this really closed? There isn't even an answer jet.

**Comment by knarfi** [comment]
I think its clear that we want to use [X, Y]. If not we can reopen the issue but I do not think this will be necessary.

**Comment by Bennyn92** [comment]
I think too, but 5 upvotes is nothing, and there wasn't even an answer jet so I was wondering.

**Comment by goto-bus-stop** [comment]
Or as A1, B7, etc, where rows are letters and columns are numbers.

I'm in favour of [X, Y], but let's keep this open until it's documented in the protocol description, and to allow other groups to leave feedback, too.

**Comment by Bennyn92** [comment]
A1, B7 etc seems fine to me. We also need to decide which are columns and which are rows then, since this sometimes is different. I'd propose this format. Then use [A, 1], [B, 2] etc.
![naamloos](https://cloud.githubusercontent.com/assets/10959531/14176266/6c741ad0-f750-11e5-9e21-3c04a39a88c5.png)

**Comment by OptOutOfSociety** [comment]
A1, B7 etc provide a good alternative as human readable format. For computer communication however this adds unnecessary complexity. 

My current favourite would be [row, col] with row and col being 0 - indexed integers.

**Comment by Bennyn92** [comment]
If whe decide to keep it human readable, it should be human readable and keep it 1 - indexed imho. However, I could live with 0 - indexed.

**Comment by knarfi** [comment]
This is about communication between computers, that should be as efficient as possible. This means using numbers and starting at 0 for indexes.
Everyone can show the server messages as they want on their own GUI.

Another given fact I do not like about using characters is that it is not determined what comes after Z, this can be AA, ZA, Z1 or anything else. Of course this can be determined but once again this makes communication a bit more unnecessarily difficult.

**Comment by goto-bus-stop** [comment]
> My current favourite would be [row, col] with row and col being 0 - indexed integers.

Sounds like we're heading this way. Is this something to discuss in a project leaders meeting, or are we happy to Just Do It™ and announce that this is how it's going to work?

**Comment by Jarinus** [comment]
Groep4: We'll vote for whichever style is preferred by most. Our code can print both types.

**Comment by Sander-Heutink** [comment]
We currently use a single continuous Integer. So for othello we have  one 0-63 integer instead of two 0-7 integers.

**Comment by OptOutOfSociety** [comment]
@Sander-Heutink Since it's a square board game it's easy to convert the values.

**Comment by Sander-Heutink** [comment]
Indeed, so i'm wondering why we dont just go with the established protocol and use a single integer/string.

**Comment by OptOutOfSociety** [comment]
There no move format declared in the established protocol that's why we are having this discussion.

**Comment by Sander-Heutink** [comment]
Wasn't it (player, string)? Or is that just in the code?

**Comment by OptOutOfSociety** [comment]
This discussion is about the format of that String

**Comment by Sander-Heutink** [comment]
Well, a lot of people want to make it a double integer, which wouldn't make it anything like a string.
but it doesn't really matter for me, so im fine either way.

**Comment by Bennyn92** [comment]
@Sander-Heutink You know, you could give integers as a string. We don't want to change the command. Just make sure that server can read the format. That means we need to have a protocol for that format.

**Comment by IcyPalm** [comment]
We need to check the current game modules what they do and base our code on that I think. Though we will discuss this in the Project leaders meeting tomorrow

**Comment by IcyPalm** [comment]
During the meeting we have chosen for the 

>  [row, col] with row and col being 0 - indexed integers 

method

**Comment by Rkallenkoot** [comment]
## Current Gamemodules behaviour works as follows:

C = Client
S = Server

The command: ```MOVE <Position>```

#### Reversi

C: MOVE 63

Server interprets this as:
```
int row = 63 / 8 = 7
int col = 63 % 8 = 7
```

```<Position>``` being >= 0 and < 64

#### Tic Tac Toe

Same as above with ```<Position>``` being >= 0 and < 9

Perhaps we could discuss this _issue_ further

**Comment by knarfi** [comment]
@Rkallenkoot Mmhhh... As long as we use the standard modules we should use the integer way of describing a move... I am not really agreeing with it but we do not really have any other choice, unless the game modules are rewritten.

What do other people think of this?

**Comment by goto-bus-stop** [comment]
@Rkallenkoot Would you mind sending a PR to document this in the [Protocol document][protocol]? Then we can point people there if a group implemented it incorrectly :stuck_out_tongue_winking_eye: 

[protocol]: https://github.com/IcyPalm/Hanze-TwoPlayerGameServer/blob/master/doc/protocol.md
