### ISSUE TITLE
Server functionaliteit

### ISSUE THREAD

**Issue by KvdV96** [IcyPalm/Hanze-TwoPlayerGameServer#17]
**Hoe werkt het kiezen van een partij (wie begint)?**
Wat als beide spelers hetzelfde kiezen, of laten we de server dit zelf random bepalen?
Hoe werkt dit na een rematch? Wordt er dan automatisch geswitcht?
**Rematch**
Komt er een mogelijkheid tot een rematch?
**Moet er altijd worden ingelogd voor het kiezen van een spel?**
Op dit moment kun je niet lokaal spelen wanneer er niet is ingelogd. Blijft dit zo?

**Comment by johankladder** [comment]
Kiezen van een speler in een spel gebeurt random:

```java
	public void acceptChallenge(Challenge challenge) {
		cancelChallenge(challenge, false);
		
		// Randomize player order
		ArrayList<Client> players = new ArrayList<Client>();
		players.add(challenge.getPlayer());
		players.add(challenge.getOpponent());
		Collections.shuffle(players);
		
		// Start the match
		Match match = createMatch(challenge.getGameType(), players.get(0), players.get(1));
		match.start();
	}
```

Rematch:

-  Op dit moment kan dit alleen wanneer je opnieuw "challenged" zegmaar. Opzich zou dit kunnen worden afgehandeld op de clientside, aangezien je gewoon een nieuwe challenge kan vragen aan de opponent en deze kan deze 'rematch' weigeren of accepteren.

Inloggen voor t spelen:

``` 
challenge "hoi" "Guess Game"
ERR Not logged in
```

**Comment by KvdV96** [comment]
Dan kan het voorkomen dat iemand meerdere keren als eerste mag beginnen. Als er wordt bijgehouden wie er in de vorige game begon zou dit afgewisseld kunnen worden.
