### ISSUE TITLE
Desciption

### ISSUE THREAD

**Issue by roffel** [IcyPalm/Hanze-TwoPlayerGameServer#18]
There is a 'R' missing in the getDesciption method in all CommandHandler classes. I think it should be getDescription.

![schermafbeelding 2016-04-01 om 14 16 10](https://cloud.githubusercontent.com/assets/9349165/14206591/7a4ff628-f814-11e5-8488-fbee03471619.png)

**Comment by Rkallenkoot** [comment]
Fixed this in pull request #20 , nice catch!
