### ISSUE TITLE
GET playerlist not following the protocol

### ISSUE THREAD

**Issue by OptOutOfSociety** [IcyPalm/Hanze-TwoPlayerGameServer#19]
As documented in the protocol both the Command and it's arguments should be case insensitive.
The GET playerlist command however only accepts playerlist as all lowercase, this in contrast to the GET gamelist command whic can be used in any combination of upper and lower case. 

![image](https://cloud.githubusercontent.com/assets/18028309/14213497/8e00d61e-f838-11e5-94a0-b9d7ec8a9723.png)

**Comment by johankladder** [comment]
Fixed it, sended a pull request!

**Comment by IcyPalm** [comment]
@johankladder see the comments on the pull request, it can be done easier

**Comment by johankladder** [comment]
fixing it atm
