### ISSUE TITLE
Reversi Time

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Hanze-TwoPlayerGameServer#24]
Descission time for reversi is set at 4 seconds for AI as decided in the Project Leader meeting

**Comment by johankladder** [comment]
Does the server know if a player is an AI? At this moment it doesn't and in my opinion it shouldn't. It doesn't matter if an player is an ai or just an human player for the server.

**Comment by roffel** [comment]
> Does the server know if a player is an AI? At this moment it doesn't and in my opinion it shouldn't. It doesn't matter if an player is an ai or just an human player for the server.

No the server will not know this. However, people can set another time when challenging others.

**Comment by johankladder** [comment]
They can't atm. The protocol change still hasn't been accepted.

**Comment by roffel** [comment]
It is now
