### ISSUE TITLE
Time checking

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Hanze-TwoPlayerGameServer#25]
Does the server check if the client thinking time has passed?

**Comment by KvdV96** [comment]
It should.

**Comment by johankladder** [comment]
Yes.

**Comment by johankladder** [comment]
Thats the turning time btw, see my pull request for setting the limit.

**Comment by Bennyn92** [comment]
It should. And in my opinion if the turning time passed the player resigned. (that way you are forced to make a fast AI)

**Comment by johankladder** [comment]
It is. When a player it waiting to long for a move, the person lost its game. This is handled in the turn time -> using a timer, and works flawless.

**Comment by Jarinus** [comment]
So after not responding quick enough you automatically lose?
Why doesn't the server just give the opponent the turn instead?

**Comment by johankladder** [comment]
Because the server thinks you're offline. You haven't made any move, so otherwise the other person is allowed to make two moves after each other.

**Comment by Bennyn92** [comment]
This issue should be closed, the answer has allready been given.
