### ISSUE TITLE
Protocol change

### ISSUE THREAD

**Issue by wbijen** [IcyPalm/Hanze-TwoPlayerGameServer#3]
**Protocol change for get commands:**

the server responses for "get gamelist" and "get playerlist" are currently:
C: get playerlist
S: OK
S: SVR PLAYERLIST ["<speler>", ...]

The improvement would be to first get the playerlist || gamelist and send the OK resonse last.
C: get playerlist
S: SVR PLAYERLIST ["<speler>", ...]
S: OK

This has the advantage of knowing that the playerlist has completely has been send.

**Comment by Rkallenkoot** [comment]
Seems like an odd change, since the 'OK' stands for: "Yes I understand this command" and 'ERR' stands for "Invalid Command"

**Comment by IcyPalm** [comment]
Maybe adding an extra OK after the playerlist?

C: get playerlist
S: OK
S: SVR PLAYERLIST ["", ...]
S: OK

That way you can check the validity of the command as wel as the player list

**Comment by goto-bus-stop** [comment]
`SVR PLAYERLIST`, conceptually, is a command from the server to the client, and not a response to the `GET PLAYERLIST` command. `SVR PLAYERLIST` is similar to `SVR CHALLENGE`, not similar to `OK` or `ERR`.

`GET PLAYERLIST` only needs to be OK'd. That's when you know your command is processed.

Clients can view `SVR PLAYERLIST` not as a response to a `GET` command, but as a completely separate command that updates the player list in the client state.

:-1:

**Comment by IcyPalm** [comment]
With reaction from @goto-bus-stop and no more input I consider this issue closed and wontfix
